name: Deploy Project

on:
  push:
    branches:
      - main  
      - hosting
  pull_request:
    branches:
      - main
      - hosting

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js for backend
      uses: actions/setup-node@v3
      with:
        node-version: '22.x' # Use your Node.js version

    # Install and Build Backend
    - name: Install backend dependencies
      working-directory: ./src
      run: |
        npm install
        npm run build # Optional if you have a build step for your backend

    # Set up Node.js for frontend
    - name: Set up Node.js for frontend
      uses: actions/setup-node@v3
      with:
        node-version: '22.x' # Use your Node.js version

    # Install and Build Frontend
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        npm install
        npm run build

    # Deploy Frontend and Backend
    - name: Deploy to Hosting Platform
      run: |
        npm install -g netlify-cli
        netlify deploy --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} 
          --site a4ebd1ab-9804-4e95-be45-9c6a2ab61177 
          --prod 
          --dir ./frontend/dist

 